Save diagram layout : Fix #213
RHEAGROUP/UI-DSM pull request #225
Opened 2023-01-02 15:33 UTC by nabilatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/UI-DSM/pulls) open
- [ ] I have verified that I am following the UI-DSM [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/UI-DSM/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

Fix #213 

A participant of a project is able to save a diagram layout that he define

2023-01-02 15:50 UTC, antoineatrhea requested changes
Small changes needed

2023-01-02 15:50 UTC, antoineatrhea commented on UI_DSM.Client/Components/NormalUser/Views/PhysicalFlowView.razor.cs
> +            this.disposables.Add(this.WhenAnyValue(x => x.ViewModel.IsOnSavingMode)
The collection is not dispose, please add `this.disposables.ForEach(x => x.Dispose());` inside the Dispose Method

2023-01-02 15:50 UTC, antoineatrhea commented on UI_DSM.Client/Model/DiagramNode.cs
> +        public Guid ThingId { get; set; }
Missing documentation

2023-01-02 15:50 UTC, antoineatrhea commented on UI_DSM.Server/Modules/DiagrammingConfigurationModule.cs
> +        /// <param name="context">The <see cref="HttpContext" /></param>
Missing documentation for parameter. Please also use the "string" instead of "String"

2023-01-02 17:46 UTC, alexatrhea approved these changes

2023-01-03 07:39 UTC, antoineatrhea approved these changes

2023-01-03 07:39 UTC, merged