Add visual UI components & login functionality
RHEAGROUP/UI-DSM pull request #29
Opened 2022-08-31 16:31 UTC by martinatg

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/UI-DSM/pulls) open
- [x] I have verified that I am following the UI-DSM [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/UI-DSM/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

This PR add mostly styling changes and prepares UI components for future development. It includes:

- CSS vars
- Layout components
- Button
- Input
- Login styling
- Login route guard on MainLayout

2022-09-02 06:50 UTC, antoineatrhea requested changes
Header file names needs to be renamed and small documentation still missing.

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/AppButton/AppButton.razor
> +// ConfirmCancelPopup.razor
Please change the name of the file on the header

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/AppButton/AppButton.razor
> +    protected override void OnInitialized()
Please also comment methods and all properties

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/AppInput/AppInput.razor
> +    [Parameter] public string Id { get; set; }
Comments + Header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/SearchBar/SearchBar.razor
>  // This file is part of UI-DSM.
Header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/TaskItem/TaskItem.razor
> +// ConfirmCancelPopup.razor
header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/TaskItem/TaskItem.razor
> +@code {
Comments

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/UserAvatar/UserAvatar.razor
> +// ConfirmCancelPopup.razor
Header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Components/App/UserAvatar/UserAvatar.razor
> +  [Parameter]
Comments

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Pages/LoginPage/LoginPage.razor
> +// Index.razor
Header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Pages/ReviewPage/ReviewPage.razor
> +// Copyright (c) 2022 RHEA System S.A.
Header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Shared/CleanLayout/CleanLayout.razor
>  // MainLayout.razor
Header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Shared/MainLayout/MainLayout.razor
> +	@inject NavigationManager NavigationManager
Comments

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Shared/TopMenu/TopMenu.razor
> +// ConfirmCancelPopup.razor
Header file name

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/Shared/TopMenu/TopMenu.razor
> +  bool IsUserMenuOpen { get; set; } = false;
Comments

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/ViewModels/Components/ILoginViewModel.cs
> +        void NavigateIfLoggedIn();
Comments

2022-09-02 06:50 UTC, antoineatrhea commented on UI_DSM/UI_DSM.Client/ViewModels/Components/LoginViewModel.cs
> +        public void NavigateIfLoggedIn()
Comments (same as the ILoginViewModel.cs file)

2022-09-04 12:12 UTC, martinatg commented
@antoineatrhea I updated the comments & file headers.

2022-09-06 06:50 UTC, antoineatrhea approved these changes

2022-09-06 11:56 UTC, merged